// Generated by CoffeeScript 1.4.0
(function() {
  var render, select;

  $('#search-input').focus();

  render = function(data, type) {
    console.log([data, type]);
    return data.full_name;
  };

  select = function(data, type) {
    return console.log("Selected " + data.title + "; Url: " + data.url);
  };

  $('#search-input').soulmate({
    engineKey: 'o7YDspiPRqV7szcQRQpo',
    renderCallback: render,
    minQueryLength: 2,
    maxResults: 5
  });

  $('#search-input-2').soulmate({
    engineKey: '123abc123abc123abc',
    documentTypes: ['books', 'magazines'],
    searchFields: {
      'books': ['title^3', 'author']
    },
    sortField: {
      'books': 'price'
    },
    sortDirection: {
      'books': 'asc'
    },
    fetchFields: {
      'books': ['author', 'title', 'price']
    },
    maxResults: 10,
    renderCallback: render,
    selectCallback: select,
    minQueryLength: 2,
    filters: {
      'books': {
        'in_stock': true,
        'genre': 'fiction'
      }
    },
    functionalBoosts: {
      'books': {
        'total_purchases': 'logarithmic'
      }
    },
    facets: {
      'books': ['genre']
    },
    timeout: 1500
  });

}).call(this);
